### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by learnwithalfred** [learnwithalfred/recipe-app#13]
Project link

https://github.com/users/learnwithalfred/projects/9#card-86747013

People in team 2 @learnwithalfred  and @Ney2

**Comment by FrederickMih** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :green_circle: 

- Tasks assigned to each student are distributed in a fair manner :heavy_check_mark: 
- Each requirement of the project has one corresponding card :+1: 
- The required number of columns has been added to the board :+1: 
- The GitHub issue link contains the requested information :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
